# Generated by Django 5.0.4 on 2024-04-17 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
