# Generated by Django 4.2.2 on 2024-04-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todoitem_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='todo_images/'),
        ),
    ]
